steps:

  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'ls'

  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m' # multithreading
      - 'cp'
      - '-r'
      - 'gs://vinegrape_data/data/'  # Specify the path to your data file in Cloud Storage
      - 'data/'  # destination

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/trainer:latest','-f','trainer.dockerfile','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/trainer:latest','-f','trainer.dockerfile']
